name = "Bisy"
author = "ImBisy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "744d98efd40f298f7825f428caf5c19bf2afccbeaad3dee07b76cc32f505386f"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
