#Better Crafting Recipes client settings
#Fri Sep 18 16:43:44 BST 2026
advancementCelebrationEnabled=true
alwaysShowIconRowEnabled=false
trackedRecipeIds=early_logistics_shulker_box
trackerHudEnabled=false
