# Written by BlockUI's config store. Edit it while the game is closed - the file is not
# watched, and the running game overwrites it whenever a setting changes in-game.

[gameplay]
	# minecolonies.config.enablecitizenvoices.comment [Default: true]
	enablecitizenvoices = true
	# minecolonies.config.neighborbuildingrendering.comment [Default: true]
	neighborbuildingrendering = true
	# minecolonies.config.neighborbuildingrange.comment [Default: 4, min: -2, max: 16]
	neighborbuildingrange = 4
	# minecolonies.config.buildgogglerange.comment [Default: 50, min: 1, max: 250]
	buildgogglerange = 50
	# minecolonies.config.colonyteamborders.comment [Default: true]
	colonyteamborders = true
	# minecolonies.config.holidayfeatures.comment [Default: true]
	holidayfeatures = true
	# minecolonies.config.showdyetooltips.comment [Default: true]
	showdyetooltips = true
